### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by puybaret** [rpax/MASSIS#2]
Hi,
Nice project! Please add information about the GNU General Public License under which this project is supposed to be distributed, because it's based on Sweet Home 3D project which is available under this license too (see section 2.b. of the [GNU GPL](http://www.gnu.org/licenses/gpl-2.0.txt)).
Thanks,
Emmanuel Puybaret, Sweet Home 3D developer

**Comment by rpax** [comment]
Don't worry, Emmanuel. I'll do it as soon as I can.

**Comment by puybaret** [comment]
Please don't forget, this is VERY important, moreover to avoid any confusion with the CC-BY-SA license that you seem to have chosen for http://www.massisframework.com web site.

**Comment by rpax** [comment]
Done

**Comment by puybaret** [comment]
Thanks :)
