### ISSUE TITLE
EnvironmentEditor.java does not work

### ISSUE THREAD

**Issue by bitacovir** [rpax/MASSIS#5]
Hi Rafael (I am Rafael too). I saw your interesting project of Massis and I wanted to try it.
I am not a programmer. I am an architect. But your documentation and tutorial are very clear so I was easy to follow them. 
I went through all the process to installation (JDK, Maven, Ant, Eclipse) and I had no problems. Then I followed the tutorial to create myfirstmassisproject. Once aIl the dependencies were downloaded I wanted to run EnvironmentEditor.java but it gives me errors:

First, a window shows a message saying:

Errors exist in required project(s):
myfirstmassisproject
Proceed with launch?

Then I do Proceed but nothing happens. 
In the console a message says: 
<terminated>EnvironmentEditor [Java Application] C:\Program Files\Java\jre1.8.0_111\bin\javaw.exe(23Dec.,2016, 8:43:19 pm)
Error: Could not find or load main class tutorialfollower.myfirstmassisproject.EnvironmentEditor

In problems tab there are three errors messages:

Description	Resource	Path	Location	Type

Missing artifact com.sun:tools:jar:1.5	pom.xml	/myfirstmassisproject	line 2	Maven Dependency Problem

The container 'Maven Dependencies' references non existing library 'C:\Users\Rafael\.m2\repository\com\sun\tools\1.5\tools-1.5.jar'	myfirstmassisproject		Build path	Build Path Problem

The project cannot be built until build path errors are resolved	myfirstmassisproject		Unknown	Java Problem

In the myfirstmassisproject/pom.xml there is a mark in the second line.
It says there is a missing artifacts:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

**Comment by rpax** [comment]
Try right clicking in the project and selecting Maven-->Update project

**Comment by rpax** [comment]
Maybe there is an issue with the configuration of your jdk/jre: http://stackoverflow.com/a/34903656/3315914

**Comment by rpax** [comment]
Try the solution posted here:
http://stackoverflow.com/a/8914788/3315914

**Comment by bitacovir** [comment]
> Try the solution posted here:
> http://stackoverflow.com/a/8914788/3315914

Thanks for your response.  I followed the instructions from the forum and I deleted and create a new project and now it worked. However, I could not continue with the tutorial because at the end of the paragraph 'Edit the simulation launcher class" you says "Also remove the try-catch block, which is not longer necessary". My problem is I am not programmer, so I do not know the correct syntax to edit the text.
I just changed the sentence that you showed:

                String buildingFilePath = null;
		try
		{
			
			buildingFilePath = "Tutorial1.sh3d";
		} catch (final IOException  e)
		{
			Logger.getLogger(SimulationWithUILauncher.class.getName())
					.log(Level.SEVERE, "Error when loading home. Exiting", e);
			System.exit(-1);
		} 

In addition, I had these messages in the console during the work with the EnvironmentEditor. I do not know if they are important:

3D [dev] 1.6.0-scijava-1-pre11-daily-experimental daily

Dec 24, 2016 12:54:14 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
loading class com.massisframework.sweethome3d.plugins.BuildingMetadataPlugin
loading class com.massisframework.testdata.TestDataPlugin
current-max-id: 17
Warning: Could not get charToByteConverterClass!

Thanks again for this project. Realy I want to test it.

**Comment by rpax** [comment]
The environment editor is being launched? Those warnings are not really important.

**Comment by bitacovir** [comment]
Yes. it has launched. It is working now.
But, what I need to know now is how should I edit this text? How should I remove the try-catch block?:

        String buildingFilePath = null;
	try
	{
		
		buildingFilePath = "Tutorial1.sh3d";
	} catch (final IOException  e)
	{
		Logger.getLogger(SimulationWithUILauncher.class.getName())
				.log(Level.SEVERE, "Error when loading home. Exiting", e);
		System.exit(-1);
	}

**Comment by rpax** [comment]
Remove:

```java

try
{

```

and

```java

} catch (final IOException  e)
{
	Logger.getLogger(SimulationWithUILauncher.class.getName())
			.log(Level.SEVERE, "Error when loading home. Exiting", e);
	System.exit(-1);
}

```

**Comment by rpax** [comment]
Ok. I'll mark this issue as closed. Don't hesitate to open a new one if you need it.
