### ISSUE TITLE
agent does not move

### ISSUE THREAD

**Issue by bitacovir** [rpax/MASSIS#6]
Hi. Following with the tutorial I went into the edition of the MyHelloHighLevelController to get a random movement of the agent. However, after the edition of the script and running the SimulationWithUILauncher the agent does not move at all. 
It looks like in my MyHelloHighLevelController script there are errors (Eclipse shows several redX, see picture). 
![javaw_2016-12-25_16-24-18](https://cloud.githubusercontent.com/assets/5121290/21469851/2148aaf0-cac0-11e6-94c0-df972304e9ac.png)

Here it is the full script any way: 

package tutorialfollower.myfirstmassisproject;

import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.massisframework.massis.model.agents.HighLevelController;
import com.massisframework.massis.model.agents.LowLevelAgent;
import com.massisframework.massis.model.building.SimRoom;
import com.massisframework.massis.model.location.Location;
import com.massisframework.massis.model.managers.movement.ApproachCallback;
import com.massisframework.massis.pathfinding.straightedge.FindPathResult.PathFinderErrorReason;

import com.massisframework.massis.model.agents.HighLevelController;
import com.massisframework.massis.model.agents.LowLevelAgent;

public class MyHelloHighLevelController extends HighLevelController {

	private static final long serialVersionUID = 1L;
	
	public MyHelloHighLevelController(LowLevelAgent agent, Map<String, String> metadata, String resourcesFolder) {
		super(agent, metadata, resourcesFolder);
		this.agent.setHighLevelData(this);
	}

	@Override
	public void stop() {
		/*
		 * Clean resources, threads...etc
		 */
	}

	@Override
	public void step() {
		
		if (this.currentTarget == null) {
	        /* 1 */ SimRoom currentRoom = this.agent.getRoom();
	        /* 2 */ this.currentTarget = currentRoom.getRandomLoc();
	    }

	    ApproachCallback callback = new ApproachCallback() {
	        @Override
	        public void onTargetReached(LowLevelAgent agent) {
	            // Target has been reached.
	        }

	        @Override
	        public void onSucess(LowLevelAgent agent) {
	            // Everything ok. The agent has moved a little bit.
	        }

	        @Override
	        public void onPathFinderError(PathFinderErrorReason reason) {
	            // Error!
	            Logger.getLogger(MyHelloHighLevelController.class.getName())
	               .log(Level.SEVERE,
	               "Error when approaching to {0} Reason: {1}",
	               new Object[] { currentTarget, reason });
	        }
	    };

	    /* 3 */ this.agent.approachTo(this.currentTarget, callback);
	}

**Comment by rpax** [comment]
Seems that you have not declared the variable.

**Comment by rpax** [comment]
I recommend you to read a book for learning Java. How about _Introduction to Java_?
